version: "3.8"

services:
  node:
    image: chainfliplabs/chainflip-node:berghain-1.1.1
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    user: root
    ports:
      - "127.0.0.1:9944:9944"
    volumes:
      - chaindata:/etc/chainflip/chaindata
    entrypoint:
      - /usr/local/bin/chainflip-node
    command:
      - --base-path=/etc/chainflip/chaindata
      - --chain=/etc/chainflip/berghain.chainspec.json
      - --rpc-cors=all
      - --rpc-methods=unsafe
      - --unsafe-rpc-external
      - --sync=warp

  broker:
    image: chainfliplabs/chainflip-broker-api:berghain-1.1.1
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "127.0.0.1:10997:80"
    environment:
      - RUST_LOG=info
    volumes:
      - ./chainflip/keys/broker:/etc/chainflip/keys
    entrypoint:
      - /usr/local/bin/chainflip-broker-api
    command:
      - --state_chain.ws_endpoint=ws://node:9944
    depends_on:
      - node

  lp:
    image: chainfliplabs/chainflip-lp-api:berghain-1.1.1
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "127.0.0.1:10589:80"
    environment:
      - RUST_LOG=info
    volumes:
      - ./chainflip/keys/lp:/etc/chainflip/keys
    entrypoint:
      - /usr/local/bin/chainflip-lp-api
    command:
      - --state_chain.ws_endpoint=ws://node:9944
    depends_on:
      - node

volumes:
  chaindata:
