services:
  node:
    image: ghcr.io/chainflip-io/chainflip-backend/chainflip-node:latest
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    user: root
    ports:
      - "127.0.0.1:9944:9944"
    entrypoint: /bin/sh
    command: >
      -c '
      /usr/local/bin/chainflip-node \
        --base-path=/etc/chainflip/chaindata \
        --chain=/etc/chainflip/berghain.chainspec.json \
        --rpc-cors=all \
        --rpc-methods=unsafe \
        --max-runtime-instances=32 \
        --unsafe-rpc-external \
        --sync=warp'
    profiles:
      - rpc-node

  node-with-broker:
    image: ghcr.io/chainflip-io/chainflip-backend/chainflip-node:latest
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    user: root
    ports:
      - "127.0.0.1:9944:9944"
    volumes:
      - ./chainflip/keys/broker:/etc/chainflip-keys/broker
    entrypoint: /bin/sh
    command: >
      -c '
      /usr/local/bin/chainflip-node key insert \
        --chain=/etc/chainflip/berghain.chainspec.json \
        --base-path=/etc/chainflip/chaindata \
        --suri=0x$$(cat /etc/chainflip-keys/broker/signing_key_file) \
        --key-type=brok \
        --scheme=sr25519 &&
      /usr/local/bin/chainflip-node \
        --base-path=/etc/chainflip/chaindata \
        --chain=/etc/chainflip/berghain.chainspec.json \
        --rpc-cors=all \
        --rpc-methods=unsafe \
        --max-runtime-instances=32 \
        --unsafe-rpc-external \
        --sync=warp
      '
    profiles:
      - broker

  node-with-lp:
    image: ghcr.io/chainflip-io/chainflip-backend/chainflip-node:latest
    pull_policy: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    platform: linux/amd64
    restart: unless-stopped
    user: root
    ports:
      - "127.0.0.1:9944:9944"
    volumes:
      - ./chainflip/keys/lp:/etc/chainflip-keys/lp
    entrypoint: /bin/sh
    command: >
      -c '
      /usr/local/bin/chainflip-node key insert \
        --chain=/etc/chainflip/berghain.chainspec.json \
        --base-path=/etc/chainflip/chaindata \
        --suri=0x$$(cat /etc/chainflip-keys/lp/signing_key_file) \
        --key-type=lqpr \
        --scheme=sr25519 &&
      /usr/local/bin/chainflip-node \
        --base-path=/etc/chainflip/chaindata \
        --chain=/etc/chainflip/berghain.chainspec.json \
        --rpc-cors=all \
        --rpc-methods=unsafe \
        --max-runtime-instances=32 \
        --unsafe-rpc-external \
        --sync=warp
      '
    profiles:
      - lp
